version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  versioning-strategy: increase
- package-ecosystem: npm
  directory: "/benchmarks"
  schedule:
    interval: daily
    time: "20:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: karma-webpack
    versions:
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
  - dependency-name: webpack
    versions:
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: dateformat
    versions:
    - 4.5.0
