version: 2
jobs:
  benchmark:
    docker:
      - image: circleci/node:8-jessie-browsers
    steps:
      - checkout
      - run:
          command: |
            cd benchmarks
            yarn install && yarn benchmark
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - save_cache:
          paths:
            - lib
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn test && yarn codecov
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: v1-build-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm publish

workflows:
  version: 2
  benchmark:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
    jobs:
      - benchmark
  build-test-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
            - test
          filters:
            tags:
              only: /v\d+(\.\d+)*/
            branches:
              ignore: /.*/
      - benchmark:
          requires:
            - deploy
          filters:
            tags:
              only: /v\d+(\.\d+)*/
            branches:
              ignore: /.*/
